<a href="https://colab.research.google.com/github/alvarenga-io/projeto-inadimplencia-pandas/blob/main/01_limpeza_e_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Predição de Bons Pagadores de Crédito

##1. Bibliotecas

In [2]:
import pandas as pd

##2. Carregando Dados

In [3]:
df = pd.read_excel('https://github.com/TrainingByPackt/Data-Science-Projects-with-Python/raw/refs/heads/master/Data/default_of_credit_card_clients__courseware_version_1_21_19.xls')

##3. Verificando a integridade dos dados

###3.1 Verificando as colunas

In [4]:
print(df.columns)
len(df.columns)

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

25

####3.1.1 Dicionário de dados



| Coluna | Nome Original | Descrição Traduzida |
| :--- | :--- | :--- |
| **X1** | LIMIT_BAL | Valor do crédito concedido (Dólar NT) |
| **X2** | SEX | Gênero (1=M, 2=F) |
| **X3** | EDUCATION | Escolaridade (1=Pós, 2=Uni, 3=Médio, 4=Outros) |
| **X4** | MARRIAGE | Estado Civil (1=Casado, 2=Solteiro, 3=Outros) |
| **X5** | AGE | Idade (Anos) |
| **X6-X11** | PAY_0-6 | Status de pagamento Set a Abr/2005 (-1: Em dia; 1-9: Meses de atraso). |
| **X12-X17** | BILL_AMT1-6 | Valor da fatura (Set a Abr/2005) |
| **X18-X23** | PAY_AMT1-6 | Valor pago (Set a Abr/2005) |
| **Target** | default.payment.next.month | Inadimplência no mês seguinte (1=Sim, 0=Não) |

###3.2 Exibição

In [5]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

###3.3 Verificando se os IDs são únicos

In [6]:
df['ID'].nunique()

29687

###3.5 Contagem de IDs

In [7]:
id_counts = df['ID'].value_counts()
id_counts.head()

ID
89f8f447-fca8    2
7c9b7473-cc2f    2
90330d02-82d9    2
75938fec-e5ec    2
2a793ecf-05c6    2
Name: count, dtype: int64

###3.6 Contagem de Duplicatas

In [8]:
id_counts.value_counts()

count
1    29374
2      313
Name: count, dtype: int64

##4. Análise das Duplicatas

###4.1 IDs que se repetem

In [9]:
dupe_mask = id_counts == 2
dupe_mask

ID
89f8f447-fca8     True
7c9b7473-cc2f     True
90330d02-82d9     True
75938fec-e5ec     True
2a793ecf-05c6     True
                 ...
bd737997-0eb0    False
6d4101a3-72cb    False
ffba3018-ce71    False
df11c637-f8c2    False
ef4d40c5-8697    False
Name: count, Length: 29687, dtype: bool

###4.2 Selecionar os IDs duplicados

In [11]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids

Index(['89f8f447-fca8', '7c9b7473-cc2f', '90330d02-82d9', '75938fec-e5ec',
       '2a793ecf-05c6', 'b44b81b2-7789', '7be61027-a493', '998fa9b2-b341',
       'a3a5c0fc-fdd6', '4e2380e6-a8cf',
       ...
       'b6ca3733-7459', '4f249cbc-5e9c', '3fddeb07-b7f0', '63338f74-01be',
       '327d06d5-ce7f', '71b5009c-75c8', 'b4937915-ad67', 'fc73f07e-eb96',
       '2a8ad33f-fa9c', '841ae407-dc4c'],
      dtype='object', name='ID', length=313)

###4.3 Transformar o index em lista

In [12]:
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

###4.4 Exibição

In [13]:
dupe_ids[:5]

['89f8f447-fca8',
 '7c9b7473-cc2f',
 '90330d02-82d9',
 '75938fec-e5ec',
 '2a793ecf-05c6']

###4.5 Selecionando linhas com IDS duplicados

In [38]:
df.loc[df['ID'].isin(dupe_ids), :].tail(10)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
29490,e7cd8c1a-88e9,320000,1,1,2,28,-2,-2,-2,-2,...,360,0,720,3894,360,360,0,720,334,0
29550,9e6e766d-ba75,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29570,f12b9d9e-ada0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29590,e7cd8c1a-88e9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29646,90330d02-82d9,70000,1,2,1,29,0,0,0,0,...,10694,27908,11192,2009,1404,3016,20001,2000,5002,0
29685,ad23fe5c-7b09,50000,1,3,1,32,0,0,0,0,...,12882,8131,3983,3000,2871,1000,163,3983,3771,1
29746,90330d02-82d9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29785,ad23fe5c-7b09,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29875,97d1d2eb-c72f,280000,1,1,1,31,0,0,0,0,...,149816,128721,130406,8900,8100,7200,5000,5000,4700,0
29975,97d1d2eb-c72f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

###4.6 Preparando a matriz booleana para filtragem do datafram

In [15]:
df_zero_mask = df == 0
df_zero_mask

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,True,True,True,True,False
1,False,False,False,False,False,False,False,False,True,True,...,False,False,False,True,False,False,False,True,False,False
2,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,True
29996,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,True,True
29997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
29998,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
29999,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False

###4.7 Criando uma série booleana

In [27]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
feature_zero_mask.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

###4.8 Visualizar linhas zeradas

In [28]:
zero_lines = df[feature_zero_mask]
zero_lines

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
241,26bde6da-f148,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
296,42009c72-651f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
423,73ed1381-3a3f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
440,4f95b36b-ab10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,8d3a2576-a958,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29570,f12b9d9e-ada0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29590,e7cd8c1a-88e9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29746,90330d02-82d9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29785,ad23fe5c-7b09,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29975,97d1d2eb-c72f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

###4.9 Eliminar duplicatas

In [30]:
df_cleaned = df.loc[~feature_zero_mask,:].copy()

###4.10 Verificar shape do Dataframe

In [33]:
df_cleaned.shape

(29685, 25)

In [34]:
df_cleaned['ID'].nunique()

29685

##5. Exploração e Limpeza de Dados

###5.1 Verificar tipos de dados do Dataset

In [ ]:
df_cleaned.reset_index(drop=True)

In [45]:
feature_zero_mask.value_counts()

False    29685
True       315
Name: count, dtype: int64

In [36]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29685 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          29685 non-null  object
 1   LIMIT_BAL                   29685 non-null  int64
 2   SEX                         29685 non-null  int64
 3   EDUCATION                   29685 non-null  int64
 4   MARRIAGE                    29685 non-null  int64
 5   AGE                         29685 non-null  int64
 6   PAY_1                       29685 non-null  object
 7   PAY_2                       29685 non-null  int64
 8   PAY_3                       29685 non-null  int64
 9   PAY_4                       29685 non-null  int64
 10  PAY_5                       29685 non-null  int64
 11  PAY_6                       29685 non-null  int64
 12  BILL_AMT1                   29685 non-null  int64
 13  BILL_AMT2                   29685 non-null  int64
 14  BILL_AMT3                   29685 non-null  int64
 15  BILL_AMT4                   29685 non-null  int64
 16  BILL_AMT5                   29685 non-null  int64
 17  BILL_AMT6                   29685 non-null  int64
 18  PAY_AMT1                    29685 non-null  int64
 19  PAY_AMT2                    29685 non-null  int64
 20  PAY_AMT3                    29685 non-null  int64
 21  PAY_AMT4                    29685 non-null  int64
 22  PAY_AMT5                    29685 non-null  int64
 23  PAY_AMT6                    29685 non-null  int64
 24  default payment next month  29685 non-null  int64
dtypes: int64(23), object(2)
memory usage: 5.9+ MB